CREATE TABLE PERSON (
"USER_NAME" VARCHAR NOT NULL,
"data"."AGE" VARCHAR,
"data"."CREATION_DATE" VARCHAR,
CONSTRAINT PERSON_PK PRIMARY KEY ("USER_NAME")
);


CREATE TABLE PURCHASE (
    "NAME1" VARCHAR NOT NULL,

    "ORDER_NUMBER1" VARCHAR NOT NULL,

    "SHIPPED1" VARCHAR NOT NULL,

   "data"."NAME2" VARCHAR,

   "data"."ORDER_NUMBER2" VARCHAR,

   "data"."SHIPPED2" VARCHAR,

   "data"."NAME3" VARCHAR,

   "data"."ORDER_NUMBER3" VARCHAR,

   "data"."SHIPPED3" VARCHAR,

   "data"."NAME4" VARCHAR,

   "data"."ORDER_NUMBER4" VARCHAR,

   "data"."SHIPPED4" VARCHAR,

   "data"."NAME5" VARCHAR,

   "data"."ORDER_NUMBER5" VARCHAR,

   "data"."SHIPPED5" VARCHAR,

   "data"."NAME6" VARCHAR,

   "data"."ORDER_NUMBER6" VARCHAR,

   "data"."SHIPPED6" VARCHAR,

    CONSTRAINT PURCHASE_PK PRIMARY KEY ( "NAME1","ORDER_NUMBER1","SHIPPED1")
);
